### ISSUE TITLE
Port this package into RT-Thread IDE

### ISSUE THREAD

**Issue by sczh01** [openLuat/luatos-soc-rtt#1]
Reqirement:
1. Add this package into RT-Thread IDE directly. Then we can import this package into our project directly, it's more usefully to promote this package.

**Comment by wendal** [comment]
@Dozingfiretruck take this ?

**Comment by PeakRacing** [comment]
> Reqirement:
> 
> 1. Add this package into RT-Thread IDE directly. Then we can import this package into our project directly, it's more usefully to promote this package.

The new version already supports IED
